/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class JniTest */

#ifndef _Included_JniTest
#define _Included_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JniTest
 * Method:    JniCallJavaMember
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JniTest_JniCallJavaMember
  (JNIEnv *, jobject);

/*
 * Class:     JniTest
 * Method:    JniCallJavaStaticMember
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JniTest_JniCallJavaStaticMember
  (JNIEnv *, jobject);

/*
 * Class:     JniTest
 * Method:    JniCallJavaMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JniTest_JniCallJavaMethod
  (JNIEnv *env, jobject jobj);

/*
 * Class:     JniTest
 * Method:    JniCallJavaStaticMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JniTest_JniCallJavaStaticMethod
  (JNIEnv *env, jobject jobj);

#ifdef __cplusplus
}
#endif
#endif
