/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class StaticRegiester */

#ifndef _Included_StaticRegiester
#define _Included_StaticRegiester
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     StaticRegiester
 * Method:    printNativeMsg
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_StaticRegiester_printNativeMsg
  (JNIEnv *, jobject);

/*
 * Class:     StaticRegiester
 * Method:    obtainNativeReturnMsg
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_StaticRegiester_obtainNativeReturnMsg
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
